appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: jW32Yh8DJfVPG54RddHQnBKXUBpX07STMvpLSkO+4Xkg4w3JCXhIOl9rY6IIEhJecoUyx8IE6OY3+g2y808EIPAxdf/vjf+jljMLArXw/fPHJqGBpkmYXldrDdrlFJGWPGDtUSyHfNWwviw0FrElka9TzCoUpDTzXDIU+EUOHgGnI7q02i3N5Kkrizhjs8voXf8pCglAW1IuwaCPtm44+qEl/efHgFq+7EHYzaCK4VKXicQhuMiw/ibilL43YvQf+RYtdW79Ol/NTNMFAdVX2W60eSOpNwwBVBEZwkx2n0ci5JKWekp0F7avjYUkavjZbhKqzcdspCPYWUHCCxa9zlOTbPeWKdgonIJFQHvJ3nTtk5xvSxcZn7W/BpTl1vLXIql9oabwxJsbQ54h4OPRaUkADurxfuwQrAYj7DqAPzkqEj9EjMUFSLADpe3KHFVmZU/3NCaRhPOLiGY/+vn21jmIIP0KvTjv4nfn2gUxXvmFj79A11/WC1D1HqM7RxRzC2aK22WYSsOMlRmzEiFpiFbkHQmtgHavozxA3VelMfObNR73Y4PdM+k6MXJRPohgPS8/svu/hXmGIhboUeGvo5BD6dRUClF5SeA85xRZN6lPpTuANcc/2RUc/bgMXa5UWTzG9mCf+M3gt+I8gbeXsZlvBSnARgdrUiDc2lfz4Tg=
conda_forge_output_validation: true
